PQ_CLIENTHELLO_MTU  # unused variable (src/blockchecks/checkers/curl_probe.py:910)
udp_latency_ms  # unused variable (src/blockchecks/checkers/dns_secure.py:201)
doh_latency_ms  # unused variable (src/blockchecks/checkers/dns_secure.py:202)
_.udp_latency_ms  # unused attribute (src/blockchecks/checkers/dns_secure.py:254)
_.doh_latency_ms  # unused attribute (src/blockchecks/checkers/dns_secure.py:263)
check_http3  # unused function (src/blockchecks/checkers/http3.py:51)
baseline_ok  # unused variable (src/blockchecks/checkers/ip_block.py:30)
_.baseline_ok  # unused attribute (src/blockchecks/checkers/ip_block.py:66)
run_ip_block_preflight  # unused function (src/blockchecks/checkers/ip_block.py:153)
pin_domains  # unused function (src/blockchecks/checkers/ip_pin.py:103)
run_l3_triage  # unused function (src/blockchecks/checkers/l3_probe.py:165)
ttl_reaches_dpi  # unused function (src/blockchecks/checkers/ttl_probe.py:40)
run_fooling_grid  # unused function (src/blockchecks/checkers/fooling_probe.py:78)
run_split_grid  # unused function (src/blockchecks/checkers/fooling_probe.py:106)
_.all_reachable  # unused property (src/blockchecks/checkers/port_block.py:25)
_.any_reachable  # unused property (src/blockchecks/checkers/port_block.py:29)
resolve_domain  # unused function (src/blockchecks/checkers/tcp_tls.py:193)
IP_DISCOVERY_TOTAL  # unused variable (src/blockchecks/checkers/udp_voice.py:17)
_.optionxform  # unused attribute (src/blockchecks/checkers/voice_discovery.py:101)
_.optionxform  # unused attribute (src/blockchecks/checkers/voice_discovery.py:115)
has_fresh_url  # unused function (src/blockchecks/checkers/youtube_url.py:178)
model_config  # unused variable (src/blockchecks/cli/cliapp.py:515)
bench_settle  # unused variable (src/blockchecks/cli/cliapp.py:531)
data_block  # unused variable (src/blockchecks/cli/cliapp.py:611)
_.cli_cmd  # unused method (src/blockchecks/cli/cliapp.py:540)
_.load_dns_records  # unused method (src/blockchecks/data_block/store.py:168)
total_enqueued  # unused variable (src/blockchecks/engine/adaptive_queue.py:102)
_.pass_rate_before_half  # unused property (src/blockchecks/engine/adaptive_queue.py:128)
neg_priority  # unused variable (src/blockchecks/engine/adaptive_queue.py:256)
seq  # unused variable (src/blockchecks/engine/adaptive_queue.py:257)
_.total_enqueued  # unused attribute (src/blockchecks/engine/adaptive_queue.py:292)
GREY  # unused variable (src/blockchecks/engine/async_runner.py:35)
_.rst_in_ttl  # unused attribute (src/blockchecks/engine/async_runner.py:552)
_.test_udp  # unused method (src/blockchecks/engine/async_runner.py:703)
BaseInNsWorker  # unused class (src/blockchecks/engine/base_worker.py:67)
FLOWSEAL_CORE_ALIASES  # unused variable (src/blockchecks/engine/blob_aliases.py:58)
include_http  # unused variable (src/blockchecks/engine/byedpi_matrix_generator.py:92)
TRANSLATION_NONE  # unused variable (src/blockchecks/engine/byedpi_translator.py:38)
quality  # unused variable (src/blockchecks/engine/byedpi_translator.py:46)
translate_or_skip  # unused function (src/blockchecks/engine/byedpi_translator.py:310)
supported_families  # unused function (src/blockchecks/engine/byedpi_translator.py:316)
is_supported  # unused function (src/blockchecks/engine/byedpi_translator.py:321)
PACKAGE_DIR  # unused variable (src/blockchecks/engine/config.py:40)
LUA_INIT_SCRIPTS  # unused variable (src/blockchecks/engine/config.py:101)
LUA_INIT_SCRIPTS  # unused variable (src/blockchecks/engine/config.py:174)
NFQWS2_READY_TIMEOUT  # unused variable (src/blockchecks/engine/config.py:210)
SUDO_WALL_TIMEOUT  # unused variable (src/blockchecks/engine/config.py:212)
BRIDGE_WS_TIMEOUT  # unused variable (src/blockchecks/engine/config.py:214)
SINGBOX_STOP_TIMEOUT  # unused variable (src/blockchecks/engine/config.py:216)
PROBE_DEFAULT_TIMEOUT  # unused variable (src/blockchecks/engine/config.py:220)
MIN_REDIRECT_LENGTH  # unused variable (src/blockchecks/engine/config.py:342)
FULL_COVERAGE_FILE  # unused variable (src/blockchecks/engine/domain_loader.py:27)
denylist_applied  # unused variable (src/blockchecks/engine/domain_loader.py:42)
is_domain_preset_file  # unused function (src/blockchecks/engine/domain_loader.py:50)
TLS_FAKE_ALERT  # unused variable (src/blockchecks/engine/fail_phase.py:36)
BANDWIDTH_THROTTLED  # unused variable (src/blockchecks/engine/fail_phase.py:57)
_._missing_  # unused method (src/blockchecks/engine/fail_phase.py:70)
_._name_  # unused attribute (src/blockchecks/engine/fail_phase.py:76)
_._value_  # unused attribute (src/blockchecks/engine/fail_phase.py:77)
need_fake  # unused variable (src/blockchecks/engine/family_needs.py:101)
need_multidisorder  # unused variable (src/blockchecks/engine/family_needs.py:104)
_.need_fake  # unused attribute (src/blockchecks/engine/family_needs.py:111)
_.need_multidisorder  # unused attribute (src/blockchecks/engine/family_needs.py:116)
foolings  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:68)
ttl_static  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:70)
ttl_auto  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:71)
tls_mods  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:73)
ack_drop  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:74)
send_md5  # unused variable (src/blockchecks/engine/generators/families/_helpers.py:75)
_.from_family  # unused method (src/blockchecks/engine/generators/families/_helpers.py:77)
_._fam_fake  # unused method (src/blockchecks/engine/generators/families/fake.py:15)
_._fam_hostfake  # unused method (src/blockchecks/engine/generators/families/fake.py:69)
_._fam_multi_fake  # unused method (src/blockchecks/engine/generators/families/fake.py:99)
_._fam_triple_fake  # unused method (src/blockchecks/engine/generators/families/fake.py:120)
_._fam_fake_multidisorder  # unused method (src/blockchecks/engine/generators/families/fake.py:141)
_._fam_fake_hostfake  # unused method (src/blockchecks/engine/generators/families/fake.py:155)
_._fam_rst_fake  # unused method (src/blockchecks/engine/generators/families/fake.py:177)
_._fam_synack  # unused method (src/blockchecks/engine/generators/families/fake.py:193)
_._fam_multisplit  # unused method (src/blockchecks/engine/generators/families/split.py:15)
_._fam_multidisorder  # unused method (src/blockchecks/engine/generators/families/split.py:51)
_._fam_fakedsplit  # unused method (src/blockchecks/engine/generators/families/split.py:72)
_._fam_fakeddisorder  # unused method (src/blockchecks/engine/generators/families/split.py:92)
_._fam_fake_multisplit  # unused method (src/blockchecks/engine/generators/families/split.py:112)
_._fam_fake_multisplit_hostfake  # unused method (src/blockchecks/engine/generators/families/split.py:137)
_._fam_fake_fakedsplit  # unused method (src/blockchecks/engine/generators/families/split.py:163)
_._fam_tcp_ipfrag  # unused method (src/blockchecks/engine/generators/families/split.py:184)
_._fam_quic_ipfrag  # unused method (src/blockchecks/engine/generators/families/split.py:221)
_._fam_syndata  # unused method (src/blockchecks/engine/generators/families/tamper.py:22)
_._fam_tcpseg  # unused method (src/blockchecks/engine/generators/families/tamper.py:46)
_._fam_oob  # unused method (src/blockchecks/engine/generators/families/tamper.py:56)
_._fam_geneva_fool  # unused method (src/blockchecks/engine/generators/families/tamper.py:69)
_._fam_wssize  # unused method (src/blockchecks/engine/generators/families/tamper.py:81)
_._fam_http_simple  # unused method (src/blockchecks/engine/generators/families/tamper.py:95)
_._fam_http_fake  # unused method (src/blockchecks/engine/generators/families/tamper.py:104)
_._fam_http_tls_dual  # unused method (src/blockchecks/engine/generators/families/tamper.py:118)
_._fam_quic_fake  # unused method (src/blockchecks/engine/generators/families/tamper.py:131)
_._fam_quic_gv  # unused method (src/blockchecks/engine/generators/families/tamper.py:153)
_._fam_udp_discord  # unused method (src/blockchecks/engine/generators/families/tamper.py:164)
_._fam_udp_quic  # unused method (src/blockchecks/engine/generators/families/tamper.py:190)
_._fam_udp_game  # unused method (src/blockchecks/engine/generators/families/tamper.py:207)
_._fam_udp_multiblob  # unused method (src/blockchecks/engine/generators/families/tamper.py:226)
TLS_MOD_NONE  # unused variable (src/blockchecks/engine/generators/flowseal.py:28)
_.generate_pairs  # unused method (src/blockchecks/engine/matrix_generator.py:232)
subprocess_env  # unused function (src/blockchecks/engine/paths.py:311)
baseline_ok  # unused variable (src/blockchecks/engine/preflight.py:101)
run_preflight  # unused function (src/blockchecks/engine/preflight.py:204)
run_prolog  # unused function (src/blockchecks/engine/preflight.py:206)
_.baseline_ok  # unused attribute (src/blockchecks/engine/preflight.py:292)
rst_in_ttl  # unused variable (src/blockchecks/engine/results.py:30)
voice_info  # unused variable (src/blockchecks/engine/results.py:82)
_.expired  # unused method (src/blockchecks/engine/run_deadline.py:119)
_.remaining_sec  # unused method (src/blockchecks/engine/run_deadline.py:128)
write_secure_text  # unused function (src/blockchecks/engine/secure_io.py:8)
model_config  # unused variable (src/blockchecks/engine/settings.py:30)
_.settle_max_for  # unused method (src/blockchecks/engine/settle_profile.py:48)
_.curl_timeout_for  # unused method (src/blockchecks/engine/settle_profile.py:52)
_.get_working_quic  # unused method (src/blockchecks/engine/store/__init__.py:73)
_.get_working_quic  # unused method (src/blockchecks/engine/store/sqlite_store.py:481)
time_total_ms  # unused variable (src/blockchecks/engine/test_runner.py:22)
_.time_total_ms  # unused attribute (src/blockchecks/engine/test_runner.py:201)
_.time_total_ms  # unused attribute (src/blockchecks/engine/test_runner.py:232)
_.time_total_ms  # unused attribute (src/blockchecks/engine/test_runner.py:338)
_.to_context  # unused method (src/blockchecks/engine/triage.py:116)
l3_status  # unused variable (src/blockchecks/mcp/server.py:57)
quic_blocked  # unused variable (src/blockchecks/mcp/server.py:60)
dns_tampered  # unused variable (src/blockchecks/mcp/server.py:61)
recommended_generators  # unused variable (src/blockchecks/mcp/server.py:62)
bytes_read  # unused variable (src/blockchecks/mcp/server.py:71)
rst_in_ttl  # unused variable (src/blockchecks/mcp/server.py:73)
raw_error  # unused variable (src/blockchecks/mcp/server.py:74)
rst_in_detected  # unused variable (src/blockchecks/mcp/server.py:82)
rst_in_ttl  # unused variable (src/blockchecks/mcp/server.py:83)
raw_strategy  # unused variable (src/blockchecks/mcp/server.py:87)
is_valid  # unused variable (src/blockchecks/mcp/server.py:88)
parsed_tokens  # unused variable (src/blockchecks/mcp/server.py:89)
escaped_conf_lines  # unused variable (src/blockchecks/mcp/server.py:90)
detected_conflicts  # unused variable (src/blockchecks/mcp/server.py:91)
triage_domain  # unused function (src/blockchecks/mcp/server.py:149)
find_working_strategy  # unused function (src/blockchecks/mcp/server.py:173)
generate_router_config  # unused function (src/blockchecks/mcp/server.py:209)
get_service_status  # unused function (src/blockchecks/mcp/server.py:235)
get_series_status  # unused function (src/blockchecks/mcp/server.py:247)
query_strategies  # unused function (src/blockchecks/mcp/server.py:404)
get_presets  # unused function (src/blockchecks/mcp/server.py:463)
stop_campaign  # unused function (src/blockchecks/mcp/server.py:500)
dbg_probe_raw  # unused function (src/blockchecks/mcp/server.py:534)
dbg_inspect_lua_ipc  # unused function (src/blockchecks/mcp/server.py:585)
dbg_validate_strategy_syntax  # unused function (src/blockchecks/mcp/server.py:619)
dbg_dump_pool_state  # unused function (src/blockchecks/mcp/server.py:665)
get_presets_manifest  # unused function (src/blockchecks/mcp/server.py:682)
get_active_run_telemetry  # unused function (src/blockchecks/mcp/server.py:691)
compare_classic  # unused variable (src/blockchecks/service/batch_models.py:35)
_.group_jobs_by_domain  # unused method (src/blockchecks/service/batch_scheduler.py:26)
recycled  # unused variable (src/blockchecks/service/batch_service.py:186)
recycled  # unused variable (src/blockchecks/service/batch_service.py:195)
recycled  # unused variable (src/blockchecks/service/batch_service.py:206)
id  # unused variable (src/blockchecks/service/lua_bridge_ipc.py:18)
_.strategy_gen  # unused property (src/blockchecks/service/lua_bridge_ipc.py:56)
_.strategy_cmd  # unused property (src/blockchecks/service/lua_bridge_ipc.py:60)
_.strategy_ready  # unused property (src/blockchecks/service/lua_bridge_ipc.py:64)
_._qnum  # unused attribute (src/blockchecks/service/nfqws2.py:136)
_._qnum  # unused attribute (src/blockchecks/service/nfqws2.py:204)
make_service  # unused function (src/blockchecks/service/server.py:429)
import_shortlist_async  # unused function (src/blockchecks/shortlist_import.py:138)
validate_strategies  # public batch API (engine/static_validator), used by MCP/CLI consumers
get_nfqws2_status  # MCP tool (LAYER C, registered via @mcp.tool)
get_zapret2_config  # MCP tool (LAYER C)
list_zapret2_blobs  # MCP tool (LAYER C)
get_ipset_status  # MCP tool (LAYER C)
probe_strategy  # MCP tool (LAYER C)
set_debug_mode  # MCP tool (LAYER A)
get_log_tail  # MCP tool (LAYER A)
get_campaign_domains_summary  # MCP tool (LAYER A2)
get_provider_profile  # MCP tool (LAYER C)
C  # terminal color namespace
heading  # terminal helper
eprint  # terminal helper
time_limit_h  # RunSpec dataclass field
time_limit_m  # RunSpec dataclass field
raw_args  # RunSpec dataclass field
CampaignContext  # execution context dataclass
_.coverage_score  # unused method in DAO API

get_quarantined  # DAO API for MCP/series status consumers
quarantine_domain  # DAO API — campaign quarantine persistence
domain_pass_rows  # DAO API — quarantine seeding on resume
get_live_events  # MCP tool (@mcp.tool() registration is invisible to vulture)
heartbeat_age  # LuaBridge API used by batch_service freshness gate

# harvest_batch: dataclass fields сериализуются через asdict(); row_factory — stdlib
HarvestCandidate.pass_rate
HarvestCandidate.conf_path
conn.row_factory
HarvestCandidate.attempts
