"""Hosts-analog IP pinning file (IP-PIN).

``--fixed-ip <path>`` points at a hosts-like file pinning domain -> IP:

    # generated by blockcheckS; hand-editable
    discord.com 162.159.135.232
    youtube.com 142.250.75.14

Pinned entries survive across runs (unlike a one-shot ``--fixed-ip <ip>``)
and are refreshed by auto-pin at startup when a pinned address stops
passing the TLS probe.
"""

from __future__ import annotations

import ipaddress
import os
from collections.abc import Iterable

_HEADER = "# blockcheckS pinned IPs (hosts-analog, auto-refreshed) — domain IP"


def parse_pins(text: str) -> dict[str, str]:
    """Parse hosts-analog text into {domain: ip}. Ignores # and empty lines."""
    pins: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        domain, ip = parts[0], parts[1]
        try:
            ipaddress.ip_address(ip)
        except ValueError:
            continue
        pins[domain] = ip
    return pins


def load_pins(path: str) -> dict[str, str]:
    """Load {domain: ip} from a hosts-analog file. Missing file -> {}."""
    try:
        with open(path, encoding="utf-8") as f:
            return parse_pins(f.read())
    except OSError:
        return {}


def dump_pins(pins: dict[str, str]) -> str:
    """Render {domain: ip} as hosts-analog text (stable domain sort)."""
    lines = [_HEADER]
    for domain in sorted(pins):
        ip = pins[domain]
        lines.append(f"{domain} {ip}")
    return "\n".join(lines) + "\n"


def save_pins(path: str, pins: dict[str, str]) -> None:
    """Atomically write {domain: ip} to a hosts-analog file."""
    data = dump_pins(pins)
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def merge_pins(current: dict[str, str], updates: dict[str, str]) -> dict[str, str]:
    """Return current updated with non-empty updates (union, updates win)."""
    merged = dict(current)
    for domain, ip in updates.items():
        if ip:
            merged[domain] = ip
    return merged


def pin_domains(pins: dict[str, str], domains: Iterable[str]) -> list[str]:
    """Domains present in the pin file (subset of the given domains)."""
    wanted = set(domains)
    return [d for d in pins if d in wanted]
