"""Hosts-like domain to IP pin file.
Accepts both 'IP domain' and 'domain IP'. Writes Windows hosts order (IP then domain).
"""

from __future__ import annotations

import ipaddress
import os
from collections.abc import Iterable
from pathlib import Path

_HEADERS = (
    "# Generated by blockcheckS — verified DoH records (anti-hijack).",
    "# Copy to C:\\Windows\\System32\\drivers\\etc\\hosts on Windows.",
    "# Auto-refreshed by blockcheckS IP pinning; hand-editable.",
)


def _is_ip(token: str) -> bool:
    try:
        ipaddress.ip_address(token)
        return True
    except ValueError:
        return False


def parse_pins(text: str) -> dict[str, str]:
    """Parse hosts-analog text into {domain: ip}.

    Accepts both ``domain IP`` and ``IP domain`` orders; ignores comments.
    """
    pins: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        if _is_ip(parts[0]):
            ip, domain = parts[0], parts[1]
        elif _is_ip(parts[1]):
            domain, ip = parts[0], parts[1]
        else:
            continue
        pins[domain] = ip
    return pins


def load_pins(path: str) -> dict[str, str]:
    """Load {domain: ip} from a hosts-analog file. Missing file -> {}."""
    try:
        with open(path, encoding="utf-8") as f:
            return parse_pins(f.read())
    except OSError:
        return {}


def dump_pins(pins: dict[str, str]) -> str:
    """Render {domain: ip} as Windows hosts text (``IP\\tdomain``, sorted)."""
    lines = list(_HEADERS)
    for domain in sorted(pins):
        ip = pins[domain]
        lines.append(f"{ip}\t{domain}")
    return "\n".join(lines) + "\n"


def save_pins(path: str, pins: dict[str, str]) -> None:
    """Atomically write {domain: ip} to a hosts-analog file."""
    from blockchecks.engine.paths import reclaim_sudo_ownership

    data = dump_pins(pins)
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    reclaim_sudo_ownership(Path(path))


def merge_pins(current: dict[str, str], updates: dict[str, str]) -> dict[str, str]:
    """Return current updated with non-empty updates (union, updates win)."""
    merged = dict(current)
    for domain, ip in updates.items():
        if ip:
            merged[domain] = ip
    return merged


def pin_domains(pins: dict[str, str], domains: Iterable[str]) -> list[str]:
    """Domains present in the pin file (subset of the given domains)."""
    wanted = set(domains)
    return [d for d in pins if d in wanted]
