# ALT12: mixed fake+multisplit(discord) + hostfakesplit(google)
--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=max_ru:@//opt/zapret2/blobs/tls_clienthello_max_ru.bin
--blob=google:@//opt/zapret2/blobs/tls_clienthello_www_google_com.bin
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=fake:blob=google:repeats=8:tcp_ts=-1000
--lua-desync=multisplit:pos=1:seqovl=664:seqovl_pattern=max_ru:tcp_ts=-1000
--lua-desync=hostfakesplit:host=www.google.com:tcp_ts=-1000
