# ALT10: fake fooling=ts fake-tls=stun+4pda_to
--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=stun:@//opt/zapret2/blobs/stun.bin
--blob=p4da:@//opt/zapret2/blobs/tls_clienthello_4pda_to.bin
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=fake:blob=stun:repeats=6:tcp_ts=-1000
--lua-desync=fake:blob=p4da:repeats=6:tcp_ts=-1000
