--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=hostfakesplit:disorder_after:tcp_ts=-1000
