--qnum=200
--ipcache-lifetime=0
--bind-fix4
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=stun:@/opt/zapret2/blobs/stun.bin
--blob=max_ru:@/opt/zapret2/blobs/tls_clienthello_max_ru.bin

--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--hostlist-domains=discord.com,discord.gg,discord.media,discordapp.com,discordcdn.com,gateway.discord.gg
--lua-desync=fake:blob=stun:repeats=6:tcp_ts=-1000
--lua-desync=fake:blob=max_ru:repeats=6:tcp_ts=-1000

--new=voice
--filter-udp=50000-50100
--filter-l3=ipv4
--filter-l7=discord,stun
--blob=discord_udp:@/opt/zapret2/blobs/discord_udp.bin
--payload=discord_ip_discovery,stun,unknown
--lua-desync=fake:blob=discord_udp:repeats=6
