--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=google:@//opt/zapret2/blobs/tls_clienthello_www_google_com.bin
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=google:badsid
--lua-desync=fake:blob=google:repeats=8:badsid:tls_mod=rnd,dupsid,sni=www.google.com
