--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=p4da:@//opt/zapret2/blobs/tls_clienthello_4pda_to.bin
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=multisplit:pos=1:seqovl=568:seqovl_pattern=p4da
