# SIMPLE FAKE ALT2: fake repeats=6 fooling=ts fake-tls=stun+max_ru ★ WORKING
--qnum=200
--filter-tcp=443
--filter-l3=ipv4
--filter-l7=tls
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=stun:@//opt/zapret2/blobs/stun.bin
--blob=max_ru:@//opt/zapret2/blobs/tls_clienthello_max_ru.bin
--hostlist-domains=discord.com,discordapp.com,discord.media,gateway.discord.gg
--lua-desync=fake:blob=stun:repeats=6:tcp_ts=-1000
--lua-desync=fake:blob=max_ru:repeats=6:tcp_ts=-1000
