--qnum=201
--filter-udp=49152-65535
--filter-l3=ipv4
--filter-l7=discord,stun
--ipcache-lifetime=0
--lua-init=@/opt/zapret2/lua/zapret-lib.lua
--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua
--blob=discord_udp:@/opt/zapret2/blobs/discord_udp.bin
--payload=discord_ip_discovery,stun,unknown
--lua-desync=fake:blob=discord_udp:repeats=6
