"""Tests for hosts-like IP pin files."""

import os
import time
from unittest.mock import AsyncMock, patch

import pytest

from blockchecks.checkers.dns_secure import DnsRunCache
from blockchecks.checkers.ip_pin import (
    dump_pins,
    load_pins,
    merge_pins,
    parse_pins,
    save_pins,
)


@pytest.mark.unit
def test_parse_pins_domain_ip():
    text = (
        "# comment\n"
        "discord.com 162.159.135.232\n"
        "youtube.com 142.250.75.14\n"
        "\n"
        "bad.invalid not-an-ip\n"
    )
    pins = parse_pins(text)
    assert pins == {
        "discord.com": "162.159.135.232",
        "youtube.com": "142.250.75.14",
    }


@pytest.mark.unit
def test_parse_pins_ip_domain_hosts_order():
    """Real Windows hosts order (IP first) must parse identically."""
    text = (
        "# Generated by blockcheckS\n162.159.128.233\tdiscord.com\n142.251.38.100\tgoogleapis.com\n"
    )
    assert parse_pins(text) == {
        "discord.com": "162.159.128.233",
        "googleapis.com": "142.251.38.100",
    }


@pytest.mark.unit
def test_load_pins_missing_file(tmp_path):
    assert load_pins(str(tmp_path / "nope.txt")) == {}


@pytest.mark.unit
def test_save_load_roundtrip(tmp_path):
    path = str(tmp_path / "pins.conf")
    save_pins(path, {"discord.com": "1.2.3.4", "a.com": "5.6.7.8"})
    assert load_pins(path) == {"discord.com": "1.2.3.4", "a.com": "5.6.7.8"}


@pytest.mark.unit
def test_dump_pins_hosts_order_and_sorted():
    text = dump_pins({"b.com": "2.2.2.2", "a.com": "1.1.1.1"})
    assert text.index("1.1.1.1") < text.index("2.2.2.2")
    assert "\t" in text.splitlines()[-1]
    assert text.startswith("# Generated by blockcheckS")
    assert "C:\\Windows\\System32" in text


@pytest.mark.unit
def test_merge_pins_keeps_inactive_domains():
    file_pins = {
        "discord.com": "162.159.136.232",  # to be updated
        "googleapis.com": "142.251.38.100",  # not in this run — keep
        "youtube.com": "216.58.201.238",
    }
    updates = {"discord.com": "162.159.138.232"}
    merged = merge_pins(file_pins, updates)
    assert merged == {
        "discord.com": "162.159.138.232",
        "googleapis.com": "142.251.38.100",
        "youtube.com": "216.58.201.238",
    }


@pytest.mark.unit
def test_merge_pins_ignores_empty_updates():
    merged = merge_pins({"a.com": "1.1.1.1"}, {"a.com": ""})
    assert merged == {"a.com": "1.1.1.1"}


@pytest.mark.unit
def test_dns_cache_pin_priority():
    cache = DnsRunCache()
    cache.set("discord.com", ["162.159.136.232", "162.159.135.232"])
    cache.add_pin("discord.com", "162.159.135.232")
    assert cache.primary_ip("discord.com") == "162.159.135.232"
    assert cache.resolve("discord.com")[0] == "162.159.135.232"


@pytest.mark.unit
def test_dns_cache_pin_not_in_resolve():
    cache = DnsRunCache()
    cache.set("discord.com", ["162.159.136.232"])
    cache.add_pin("discord.com", "162.159.135.232")
    ips = cache.resolve("discord.com")
    assert ips[0] == "162.159.135.232"
    assert "162.159.135.232" in ips


@pytest.mark.unit
def test_dns_cache_candidates_no_pin_priority():
    cache = DnsRunCache()
    cache.set("discord.com", ["162.159.136.232", "162.159.135.232"])
    cache.add_pin("discord.com", "162.159.135.232")
    assert cache.candidates("discord.com") == [
        "162.159.136.232",
        "162.159.135.232",
    ]


@pytest.mark.unit
def test_dns_cache_set_pins_drops_empty():
    cache = DnsRunCache()
    cache.set_pins({"discord.com": "1.1.1.1", "youtube.com": ""})
    assert cache.pins() == {"discord.com": "1.1.1.1"}


@pytest.mark.unit
def test_retry_respects_short_timeout():
    """Second IP attempt uses a reduced per-IP budget (regression guard)."""
    from blockchecks.engine import async_runner

    assert 0 < async_runner.RETRY_IP_TIMEOUT <= 3.0


def _make_runner_with_cache(pins=None, entries=None):
    from blockchecks.engine.async_runner import AsyncTestRunner

    cache = DnsRunCache()
    for domain, ips in (entries or {}).items():
        cache.set(domain, ips)
    cache.set_pins(pins or {})
    runner = AsyncTestRunner(pool_size=1, dns_cache=cache, pinned_path="/tmp/pins_test.conf")
    return runner, cache


@pytest.mark.asyncio(loop_scope="package")
async def test_auto_pin_writes_only_when_changed(tmp_path):
    """Save happens only when a pin IP actually changes (git stays clean)."""

    path = str(tmp_path / "hosts")
    with open(path, "w", encoding="utf-8") as f:
        f.write("162.159.135.232\tdiscord.com\n")  # already-working pin

    runner, cache = _make_runner_with_cache(
        pins={"discord.com": "162.159.135.232"},
        entries={"discord.com": ["162.159.136.232", "162.159.135.232"]},
    )
    runner.pinned_path = path

    # pinned IP still works -> file content unchanged -> no rewrite
    with patch.object(runner, "_probe_pin_ip", new_callable=AsyncMock) as probe:
        probe.return_value = True
        await runner._auto_pin_ips()
    with open(path, encoding="utf-8") as f:
        content_before = f.read()
    mtime_before = os.path.getmtime(path)
    time.sleep(0.05)
    with patch.object(runner, "_probe_pin_ip", new_callable=AsyncMock) as probe:
        probe.return_value = True
        await runner._auto_pin_ips()
    with open(path, encoding="utf-8") as f:
        content_after = f.read()
    assert content_after == content_before
    assert os.path.getmtime(path) == mtime_before

    # pinned IP fails, fallback works -> file updated
    async def _probe(domain, ip):
        return ip == "162.159.136.232"

    with patch.object(runner, "_probe_pin_ip", new_callable=AsyncMock) as probe:
        probe.side_effect = _probe
        await runner._auto_pin_ips()
    with open(path, encoding="utf-8") as f:
        updated = f.read()
    assert "162.159.136.232\tdiscord.com" in updated
    assert "162.159.135.232" not in updated.split("\t")[0]
