name: SleepTest
on:
  workflow_dispatch:
jobs:
  sleep:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "start $(date +%s)"
      - run: sleep 60
      - run: echo "done $(date +%s)"
